### ISSUE TITLE
Can_OBD2.cpp 

### ISSUE THREAD

**Issue by peterdiffey** [damienmaguire/MG-EV-Inverter#1]
#include "Can_OBD2.h"
#include "stm32_can.h"
#include "params.h" <<<<<< not in repo

params.h does not exist, however there is a params_prj.h

I have been having trouble with getting RPM out of canbus.
I am not a C++ programmer, so I be talking tosh, but that params.h  file missing may have impact.

I note the following  in Can_OBD2.cpp
====================================
void Can_OBD2::DecodeCAN(int id, uint32_t data[2])
{
  uint8_t *bytes = (uint8_t *)data; // arrgghhh this converts the two 32bit array into bytes. See comments are useful:)
  uint8_t response[8];
  uint16_t speed;

  if (id == 0x7DF)   or better if (id == PID_REQUEST)

where does this id come from? ie who/what is sending a can msg (presumably) starting 0x7DF

====================================
      case ENGINE_RPM:
        response[0] = 0x04;
        response[2] = ENGINE_RPM;
        speed = Param::GetInt(Param::speed);   <<< is this a parameter or is this data?
        response[3] = (speed >> 8) & 0xFF;
        response[4] = (speed) & 0xFF;
        can->Send(PID_REPLY, response, 8);
        break;

Param::GetInt(Param::speed); is surely getting the value set in the webUI called speed, so it will always report whatever is set in the webUI

**Comment by damienmaguire** [comment]
This has no bearing on the MG inverter project.
